-- Only for the DISPOSABLE helper integration test database job_tracker_lab_test.
-- Never executed by lab preparation or by normal student startup.
CREATE TABLE users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 101) PRIMARY KEY,
 email TEXT NOT NULL UNIQUE, name TEXT NOT NULL
);
CREATE TABLE jobs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
 title TEXT NOT NULL, company TEXT NOT NULL,
 created_by BIGINT NOT NULL REFERENCES users(id),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE applications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id), job_id BIGINT NOT NULL REFERENCES jobs(id),
 status TEXT NOT NULL CHECK(status IN ('new','screening','interview','offer','rejected')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(user_id, job_id)
);
